### ISSUE TITLE
Automated checks not running

### ISSUE THREAD

**Issue by Zegorax** [ObjectifLibre/cabot-alert-rocketchat#3]
Hello everyone,

After installing the plugin, the checks Cabot launches automatically are not running.

Here's the worker error : 
```
[2018-10-24 13:40:09,035: ERROR/MainProcess] Received unregistered task of type 'cabot.cabotapp.tasks.run_all_checks'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
u'[[], {}, {"chord": null, "callbacks": null, "errbacks": null, "chain": null}]' (77b)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 559, in on_task_received
    strategy = strategies[type_]
KeyError: 'cabot.cabotapp.tasks.run_all_checks'
```

**Comment by fydrah** [comment]
HI @Zegorax ,

Which version of cabot do you use ?

Could you aslo provide your configuration with rocketchat plugin ?

Regards,

**Comment by Zegorax** [comment]
Hello Flavien,

I'm using the latest version of Cabot, using the Docker repo.

Here's the plugin configuration :

ROCKETCHAT_CHANNEL=#SYSTEM-STATUS
ROCKETCHAT_WEBHOOK_URL=<REDACTED>
ROCKETCHAT_USERNAME=MONITOR
ROCKETCHAT_COLLAPSED_SERVICE=False
ROCKETCHAT_COLLAPSED_CHECKS=False
ROCKETCHAT_COLLAPSED_ALERT=False

**Comment by Zegorax** [comment]
Hello,

Do you have any news about this ?

**Comment by fydrah** [comment]
Hi @Zegorax ,

Configuration is good.

It seems the image you use does not have cabot-rocket-chat plugin installed. Could you run a `pip freeze` from your worker ?

**Comment by fydrah** [comment]
Btw, If you use cabot docker-compose from the github repository, you must update "requierements-plugins.txt" with cabot-rocket-chat plugin & rebuild docker image.

You can use [this fork](https://github.com/fydrah/cabot/) for example, just re-run a docker build.

Regards,
